// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProject struct {
	Name   string `json:"name"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name   string `json:"name"`
	UserID string `json:"userId"`
}

type Project struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	User string `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
